import React from 'react'
import Link from 'next/link'

import { Icon } from 'arkade/common'
import { ScrollWatcher } from 'arkade/tools'
import { scrollSnap, isMobile } from 'arkade/utils/browser-utils'

export const CenterStageEventsSlide = (props = {}) => {
    return (
        <ScrollWatcher
            {...props}
            onCenter={(el) => isMobile ? null : scrollSnap(el.offsetTop)}
            className="grid-fluid row items-center justify-center pad-20 text-white"
            style={{ minHeight: '100vh' }}>
            <div className="margin-20" style={{ width: '300px' }}>
                <img alt="CenterStage Events logo" src="/logo-centerstage-events.png" style={{ width: '100%', padding: '10px' }} />
            </div>
            <div>
                <p className="text-large text-light text-left pad-20 margin-bottom-0" style={{ maxWidth: '600px', border: '1px solid rgba(255,255,255,0.4)' }}>
                    <b>CenterStage Events raise awareness and funding</b> for Thirty Amp Circuit’s healthcare and wellness initiatives.
                    <br/><br/>
                    In addition to revenue generated by Ticket Sales, Merchandise, Record Sales and Sponsorship, each event also creates invaluable content and marketing tools that that build a wonderful ecosystem to foster future private contributions, business development, and public awareness of the need for musicians’ healthcare.
                </p>
                <Link href="/centerstage">
                    <button className="btn btn-dark text-upper text-bold margin-top-0 margin-bottom-10">Learn more <Icon fa="angle-right margin-left-10"/></button>
                </Link>
                <div className="row margin-top-10 justify-between">
                    <div className="text-left">
                        <small className="text-teal">Last event:</small>
                        <br />
                        <h5><a href="https://liveforlivemusic.com/news/ivan-neville-birthday/">Ivan Neville: Through The Years</a></h5>
                        <h6>Live at <i>Le Petit Theatre</i></h6>
                        <p>May 2019</p>
                    </div>
                    <div className="text-right">
                        <small className="text-teal">Next event:</small>
                        <br/>
                        <h5><a href="https://www.brownpapertickets.com/event/4531655">Ivan + Anders + Stanton + George</a></h5>
                        <h6>at <i>the Ogden Museum of Southern Art</i></h6>
                        <p>April 2020</p>
                    </div>
                </div>
            </div>
        </ScrollWatcher>
    )
}
